server:
  port: 8080

spring:
  application:
    name: CareerVault-Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/career_vault
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: CareerVault-HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000 # 30s
      max-lifetime: 1800000     # 30 phút

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
#    serialization:
#      write-dates-as-timestamps: false

application:
  security:
    jwt:
      secret-key: "CHANGE_ME_TO_A_VERY_LONG_SECRET_KEY_AT_LEAST_64_CHARS_FOR_HS512"
      expiration: 86400000      # 1 ngày (ms)
      refresh-token:
        expiration: 604800000